// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpckozznwryagamsebze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwY2tvenpud3J5YWdhbXNlYnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzgxMzAsImV4cCI6MjA2MDg1NDEzMH0.ksI3NL33iI41PFz4qLaCei5obnfdMiUc2VtZFb0mO4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);